// <auto-generated>
// Generated by tools/gen_data.py from the assembled BBC Master Elite binaries.
// Do not edit by hand.
// </auto-generated>

namespace EliteSharp.Data;

public static class GameData
{
    /// <summary>SFXPR: sound data block 1.</summary>
    public static readonly byte[] SoundPriority =
    [
        0x4B, 0x5B, 0x3F, 0xEB, 0xFF, 0x09, 0xFF, 0x8B, 0xCF, 0xE7, 0xFF, 0xEF,
    ];

    /// <summary>SFXBT: sound data block 2.</summary>
    public static readonly byte[] SoundBits =
    [
        0x40, 0x10, 0x01, 0xFC, 0xF3, 0x19, 0xF9, 0x7C, 0xF1, 0xFA, 0xFE, 0xFE,
    ];

    /// <summary>SFXFQ: sound data block 3.</summary>
    public static readonly byte[] SoundFrequency =
    [
        0xF0, 0x20, 0x10, 0x30, 0x03, 0x01, 0x08, 0x80, 0x16, 0x38, 0x00, 0x80,
    ];

    /// <summary>SFXVC: sound data block 4.</summary>
    public static readonly byte[] SoundVolumeChange =
    [
        0xFF, 0xFF, 0x00, 0x03, 0x1F, 0x01, 0x07, 0x07, 0x0F, 0x03, 0x0F, 0x0F,
    ];

}
