#!/usr/bin/env python3
"""
Generates the C# data files for EliteSharp from the BBC Master Elite source.

The data tables (the font, the hangar and the sound data) are lifted
byte-for-byte from the assembled binaries, using the label addresses in the
assembler listing, so the port uses exactly the same data as the game. The
dashboard and its bulbs (P.DIALS2P, ECBT and SPBT) are PNG images in
src/EliteSharp/Assets/Images, which the tests check against the original. The ships are exported separately, as assets, by
tools/export_ships.py.

The markets and equipment prices (QQ23 and PRXS) are in
src/EliteSharp/Assets/trading.yml, and the default commander (NA%), the energy
bomb's bolt (BOMBPOS) and the pause keys (TGINT) are in the game's code; the
tests check them against the original bytes.

The original's text token tables aren't needed: the game's fixed text and the
system descriptions are in src/EliteSharp/Assets/Strings, the missions' text is
in src/EliteSharp/Assets/Missions, and the letters of the systems' names
(QQ16) are in the game's code (Game/SystemNames.cs).

Usage: python tools/gen_data.py   (run from the repository root)
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "elite-source-code-bbc-master")

LISTING = os.path.join(SRC, "3-assembled-output", "compile.txt")
BCODE = os.path.join(SRC, "3-assembled-output", "BCODE.unprot.bin")
BDATA = os.path.join(SRC, "3-assembled-output", "BDATA.unprot.bin")
FONT = os.path.join(SRC, "1-source-files", "fonts", "P.FONT.bin")
OUT_DIR = os.path.join(ROOT, "src", "EliteSharp", "Data")

BCODE_BASE = 0x1300
BDATA_BASE = 0x7000

# ---------------------------------------------------------------------------
# Assembler listing: label -> address
# ---------------------------------------------------------------------------

def read_labels():
    labels = {}
    lines = open(LISTING, encoding="latin-1").read().splitlines()
    for i, line in enumerate(lines):
        m = re.match(r"^\.(\S+)$", line)
        if not m:
            continue
        name = m.group(1)
        if name in labels:
            continue
        for j in range(i + 1, min(i + 40, len(lines))):
            a = re.match(r"^\s+([0-9A-F]{4})\b", lines[j])
            if a:
                labels[name] = int(a.group(1), 16)
                break
    return labels


LABELS = read_labels()
BCODE_BYTES = open(BCODE, "rb").read()
BDATA_BYTES = open(BDATA, "rb").read()


def code_bytes(label, count, offset=0):
    addr = LABELS[label] + offset - BCODE_BASE
    return list(BCODE_BYTES[addr:addr + count])


def data_bytes(label, count=None, end_label=None):
    start = LABELS[label] - BDATA_BASE
    if end_label is not None:
        end = LABELS[end_label] - BDATA_BASE
    elif count is not None:
        end = start + count
    else:
        end = len(BDATA_BYTES)
    return list(BDATA_BYTES[start:end])


# ---------------------------------------------------------------------------
# Byte tables
# ---------------------------------------------------------------------------

def fmt_bytes(name, data, comment):
    lines = [f"    /// <summary>{comment}</summary>",
             f"    public static readonly byte[] {name} ="]
    lines.append("    [")
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"        {chunk},")
    lines.append("    ];")
    lines.append("")
    return lines


def gen_tables():
    tables = []

    # Tables in the main code block (the maths tables, such as the sine,
    # arctan and logarithm tables, are left out, as the game uses real maths)
    tables.append(("HangarGroups", code_bytes("HATB", 36),
                   "HATB: ship hangar groups (type, x_hi/z_hi, z_lo/x_sign) * 3 * 4."))
    tables.append(("SoundPriority", code_bytes("SFXPR", 12), "SFXPR: sound data block 1."))
    tables.append(("SoundBits", code_bytes("SFXBT", 12), "SFXBT: sound data block 2."))
    tables.append(("SoundFrequency", code_bytes("SFXFQ", 12), "SFXFQ: sound data block 3."))
    tables.append(("SoundVolumeChange", code_bytes("SFXVC", 12), "SFXVC: sound data block 4."))
    # The colours (the palettes TVT1 and TVT3, and the colour tables coltabl
    # and sightcol) are defined as inks and palettes in the game's code (see
    # Rendering/Ink.cs and Rendering/Palette.cs), rather than as screen bytes

    tables.append(("Font", list(open(FONT, "rb").read()),
                   "FONT%: the MOS character bitmaps for ASCII 32-127."))

    out = ["// <auto-generated>",
           "// Generated by tools/gen_data.py from the assembled BBC Master Elite binaries.",
           "// Do not edit by hand.",
           "// </auto-generated>",
           "",
           "namespace EliteSharp.Data;",
           "",
           "public static class GameData",
           "{"]
    for name, data, comment in tables:
        out.extend(fmt_bytes(name, data, comment))
    out.append("}")
    return "\n".join(out)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "GameData.g.cs"), "w", newline="\n") as f:
        f.write(gen_tables() + "\n")
    print("Generated the data tables into", OUT_DIR)


if __name__ == "__main__":
    main()
